name: Pull latest code on OEL

on:
  push:
    branches: [ main ]

jobs:
  pull:
    runs-on: [self-hosted, linux, ARM64]

    steps:
      - name: Update repo on server
        run: |
          cd /home/opc/CashFlowArc
          git fetch origin
          git reset --hard origin/main